web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUserPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack

    # Phoenix uses RESTful conventions, that's why func new
    get "/", TopicController, :index
    # get "/topics/new", TopicController, :new
    # post "/topics", TopicController, :create
    # get "/topics/:id/edit", TopicController, :edit
    # put "/topics/:id", TopicController, :update
    # delete "/topics/:id", TopicController, :delete
    resources "/topics", TopicController
  end

  scope "/auth", Discuss do
    pipe_through :browser

    # route to AuthController.request function, which is inside the used Ueberauth-plug
    get "/signout", AuthController, :sign_out
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view

  def get_name(user) do
    if user.nickname, do: user.nickname, else: user.email
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    
  </head>

  <body>

    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Discussions
        </a>
        
        <%= if @conn.assigns[:user] do %>
          <figure class="image is-48x48 right" style="bottom:10px; right:20px;">
            <img src="<%= @conn.assigns.user.avatar %>">
          </figure>
          <%= link to: auth_path(@conn, :sign_out) , class: "oauth-btn right" do %>
            <button class="btn">Sign out</button>
          <% end %>
        <% else %>
          <%= link to: auth_path(@conn, :request, "github") , class: "oauth-btn right" do %>
            <button class="btn">Sign in with GitHub</button>
          <% end %>
        <% end %>


      </div>
      
      </div>
    </nav>

    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
  </body>
</html>